import Teach from '../src/Images/Teach.png';
import Teacher from '../src/Images/Teacher.jpg';

const tutors = [
  {
    id: 1,
    firstName: 'Yemi',
    lastName: 'Oshin',
    region: 'Lagos',
    city: 'Ikeja',
    homeAddress: 'Mimi street',
    age: 29,
    birthday: "3-5-1995",
    experience: '5 years',
    email: 'yemioshin567@gmail.com',
    image: Teach,
    location: 'No 7 Mimi street, Opebi',
    landmark: 'Opebi Bustop',
    rate: 'NGN3,000.00',
    subject: 'Mathematics, Basic Science, and PHE',
    grade: 'Primary six, JSS1-3, SSS1-3',
    shortWriteUp: 'Yemi Oshin has over 10 years of experience in teaching Mathematics, Science, and PHE.',
    grade2: 'Primary six :',
    grade4: 'SSS1-3 :',
    subject2: 'Mathematics',
    grade3: 'JSS 1-3 :',
    subject4: 'and PHE',
    subject3: 'Basic Science',
    education: 'Bachelor of Education',
    school: 'Obafemi Awolowo University',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 13km',
    mode: 'Physical and Online classes',
    availability: 'Available all day',
    availability2: 'Not available',
    preferred_tool: 'Google Meet',
    phone: '0803 567 7896',
    about: 'With over 10 years of experience, I specialize in teaching Mathematics, Basic Science, and PHE to various grade levels. My approach focuses on building strong foundational skills and ensuring comprehensive understanding.',
    description: 'Experienced tutor specializing in Mathematics, Basic Science, and PHE with a focus on strong foundational skills.'
  },
  {
    id: 2,
    firstName: 'Jane',
    lastName: 'Smith',
    region: 'Lagos',
    city: 'Agege',
    age: 34,
    birthday: "3-5-1995",
    experience: '5 years',
    rate: 'NGN2,500.00',
    email: 'prettyjane@gmail.com',
    image: Teacher,
    location: 'plot 7, shoyinka street',
    landmark: 'Abule Egba busstop',
    subject: 'Yoruba',
    grade: 'Primary and Secondary',
    grade2: 'Primary :',
    grade4: 'SSS1-3 :',
    subject2: 'Yoruba',
    grade3: 'JSS 1-3 :',
    subject3: 'Yoruba',
    education: 'Bachelor of Education',
    school: 'Lagos State University',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 7km',
    mode: 'Physical and Online classes',
    availability: 'Available',
    availability2: 'Available',
    preferred_tool: 'Google Meet',
    phone: '0803 237 7896',
    shortWriteUp: 'Jane Smith is passionate about teaching Yoruba.',
    about: 'I am dedicated to teaching Yoruba to students across Primary and Secondary levels, with a focus on enhancing their language skills and cultural understanding.',
    description: 'Passionate Yoruba educator with expertise in teaching the language across various grade levels.'
  },
  {
    id: 3,
    firstName: 'Ayuk',
    lastName: 'Hailey',
    region: 'Ekiti',
    city: 'Ijero Ekiti',
    age: 30,
    birthday: "3-5-1995",
    experience: '5 years',
    email: 'prettyjane@gmail.com',
    image: Teach,
    location: '9 Ijowa street, Ijero',
    landmark: 'Giwa',
    rate: 'NGN3,000.00',
    subject: 'English',
    grade: 'Primary, JSS and SSS',
    shortWriteUp: 'Ayuk Hailey has extensive experience in teaching English across multiple levels.',
    grade2: 'Primary :',
    grade4: 'SSS1-3 :',
    subject2: 'English',
    grade3: 'JSS 1-3 :',
    subject3: 'English',
    education: 'Doctor of Education',
    school: 'Mapoly',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 7km',
    mode: 'Physical and Online classes',
    availability: 'Not available',
    availability2: 'Available',
    preferred_tool: 'Google Meet',
    phone: '0706 832 5618',
    about: 'With over five years of experience, I specialize in teaching English to students at Primary, JSS, and SSS levels. My teaching method emphasizes clear communication, critical thinking, and comprehensive language skills.',
    description: 'Experienced English tutor with expertise in teaching at Primary, JSS, and SSS levels.'
  },
  {
    id: 4,
    firstName: 'Adebowale',
    lastName: 'Tumishe',
    region: 'Lagos',
    city: 'Kosofe',
    age: 30,
    birthday: "3-5-1995",
    experience: '9 years',
    email: 'ademi@gmail.com',
    image: Teach,
    location: 'Lalonpe Street, Ketu',
    landmark: 'Ketu Market',
    rate: 'NGN3,000.00',
    subject: 'Phonics, Literature, and English Language',
    grade: 'Primary, JSS, SSS',
    shortWriteUp: 'Adebowale Tumishe specializes in Phonics, Literature, and English Language, helping students develop strong reading and comprehension skills.',
    grade2: 'Primary :',
    grade4: 'SSS1-3 :',
    subject2: 'English Language',
    subject5: 'and Literature',
    subject6: 'and Phonics',
    grade3: 'JSS 1-3 :',
    subject3: 'Phonics',
    education: 'Bachelor of Education',
    school: 'Obafemi Awolowo University',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 10km (~ 60mins drive)',
    mode: 'Physical classes',
    availability: 'Available all day',
    availability2: 'Not available',
    about: 'I have extensive experience in teaching Phonics, Literature, and English Language to students across various levels. My focus is on developing strong literacy skills and a love for reading.',
    description: 'Specialized tutor in Phonics, Literature, and English Language with a focus on literacy development.'
  },
  {
    id: 5,
    firstName: 'Modupe',
    lastName: 'Alatise',
    region: 'Lagos',
    city: 'Ogba',
    age: 24,
    birthday: "3-5-1995",
    experience: '9 years',
    email: 'modupealatise89@gmail.com',
    image: Teach,
    location: '24 Coker street, Ogba',
    landmark: 'Aguda Bustop',
    rate: 'NGN4,000.00',
    subject: 'Mathematics and Business Studies',
    grade: 'Primary Six, JSS1-3, SSS1-3',
    grade2: 'Primary Six :',
    grade4: 'SSS1-3 :',
    subject2: 'Mathematics',
    grade3: 'JSS 1-3 :',
    subject3: 'Business Studies',
    education: 'Master of Business Education',
    school: 'Obafemi Awolowo University',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 11km',
    mode: 'Physical and Online classes',
    preferred_tool: 'Google Meet',
    availability: 'Not available',
    availability2: 'Available all day',
    shortWriteUp: 'Modupe Alatise offers expert guidance in Mathematics and Business Studies.',
    about: 'I provide expert instruction in Mathematics and Business Studies, focusing on practical applications and in-depth understanding to prepare students for academic and real-world challenges.',
    description: 'Expert tutor in Mathematics and Business Studies with a focus on practical applications and comprehensive understanding.'
  },
  {
    id: 6,
    firstName: 'Jasmin',
    lastName: 'Momodu',
    region: 'Lagos',
    city: 'Egbeda',
    age: 28,
    birthday: "3-5-1995",
    experience: '5 years',
    email: 'jasminmo2020@gmail.com',
    image: Teach,
    location: 'Plot 5 Ayoola street, Gemade Estate.',
    landmark: '31 Road',
    rate: 'NGN3,500.00',
    subject: 'Mathematics and Basic Technology',
    grade: 'Primary, JSS, SSS',
    shortWriteUp: 'Jasmin Momodu excels in teaching Mathematics and Basic Technology.',
    subject: 'Mathematics and Basic Technology',
    grade: 'Primary, JSS1-3, SSS 1-3',
    grade2: 'Primary :',
    grade4: 'SSS1-3 :',
    subject2: 'Mathematics',
    grade3: 'JSS 1-3 :',
    subject3: 'Basic Technology',
    education: 'Bachelor of Education',
    school: 'Obafemi Awolowo University',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 10km (~ 60mins drive)',
    mode: 'Physical classes',
    availability: 'Available all day',
    availability2: 'Not available',
    about: 'With over five years of experience, I specialize in Mathematics and Basic Technology, using innovative teaching methods to make complex concepts accessible and engaging for students.',
    description: 'Experienced tutor in Mathematics and Basic Technology with a focus on innovative teaching methods.'
  },
  {
    id: 7,
    firstName: 'Kemi',
    lastName: 'Olamide',
    region: 'Lagos',
    city: 'Olowoira',
    age: 28,
    birthday: "3-5-1995",
    experience: '2 years',
    email: 'kemkem20@gmail.com',
    image: Teach,
    location: 'plot 6 solomon close, Olowoira',
    landmark: 'Olowoira Bustop',
    rate: 'NGN3,000.00',
    subject: 'Bible Knowledge',
    grade: 'Primary, JSS1-3, SSS1-3',
    shortWriteUp: 'Kemi Olamide provides insightful teaching in Bible Knowledge for various grades.',
    grade2: 'Primary :',
    grade4: 'SSS1-3 :',
    subject2: 'Bible Knowledge',
    grade3: 'JSS 1-3 :',
    subject3: 'Bible Knowledge',
    education: 'Doctor of Education',
    school: 'University of Lagos State',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 8km',
    mode: 'Physical and Online classes',
    preferred_tool: 'Google Meet',
    availability: 'Available',
    phone: '0903 567 7896',
    availability2: 'Available all day',
    about: 'I specialize in teaching Bible Knowledge with a focus on spiritual growth and understanding. My teaching aims to provide students with a deep and meaningful grasp of biblical concepts.',
    description: 'Specialized tutor in Bible Knowledge with a focus on spiritual growth and understanding.'
  },
  {
    id: 8,
    firstName: 'Obi',
    lastName: 'Jessicah',
    region: 'Ibadan',
    city: 'Challenge',
    age: 34,
    birthday: "3-5-1995",
    experience: '2 years',
    email: 'jessicahloveleen@gmail.com',
    image: Teach,
    location: 'No 19 Alhaji Fatai street, Challenge',
    landmark: 'Okada Bustop',
    rate: 'NGN5,500.00',
    subject: 'Biology and Physics',
    grade: 'SSS1-3',
    shortWriteUp: 'Obi Jessicah is skilled in teaching Biology and Physics with extensive experience.',
    grade4: 'SSS1-3 :',
    subject5: 'Biology and Physics',
    education: 'Master of Science',
    school: 'University of Lagos State',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 8km',
    mode: 'Physical and Online classes',
    preferred_tool: 'Google Meet',
    availability: 'Available',
    phone: '0903 567 7896',
    availability2: 'Available all day',
    about: 'I offer specialized instruction in Biology and Physics, aiming to provide students with a comprehensive understanding of these sciences through engaging and practical teaching methods.',
    description: 'Experienced tutor in Biology and Physics with a focus on practical and engaging teaching methods.'
  },
  {
    id: 9,
    firstName: 'Emmanuel',
    lastName: 'Ayodele',
    location: 'No 342B Norus Close, Omole Phase 1, Ikeja, Lagos',
    email: 'ayodeleAol345@gmail.com',
    phone: '0902 367 8689',
    age: 34,
    birthday: '5-2-1995',
    experience: '8 years',
    image: Teacher,
    rate: 'NGN5,500.00',
    subject: 'Physics and Further Mathematics',
    grade: 'SSS1-3',
    shortWriteUp: 'Ayodele Emmanuel is skilled in teaching Physics and Further Mathematics with extensive experience.',
    grade4: 'SSS1-3 :',
    subject5: 'Physics and Further Mathematics',
    education: 'Bachelor of Medicine and Surgery',
    school: 'University of Ibadan',
    travel: "Classes hold at student's home",
    travel2: 'I am willing to travel for 7km',
    mode: 'Physical and Online classes',
    preferred_tool: 'Google Meet',
    availability: 'Not available',
    phone: '0903 567 7896',
    availability2: 'Available all day',
    about: 'I have eight years of experience teaching Physics and Further Mathematics, focusing on advanced problem-solving skills and exam preparation to help students excel in these challenging subjects.',
    description: 'Expert tutor in Physics and Further Mathematics with a focus on advanced problem-solving and exam preparation.'
  }
];

export default tutors;

